// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb2qLn0cVAry457HkQOPRmvcuO3SUXP0I',
    appId: '1:875660399293:web:d775671840af2b3f105dd4',
    messagingSenderId: '875660399293',
    projectId: 'run-balanced-ca5ef',
    authDomain: 'run-balanced-ca5ef.firebaseapp.com',
    storageBucket: 'run-balanced-ca5ef.firebasestorage.app',
    measurementId: 'G-YMLV3PGMXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkEYLuaKQlbo-axyJFv9hNJvJ733nkP0A',
    appId: '1:875660399293:android:7a4ed27a5a2bd18a105dd4',
    messagingSenderId: '875660399293',
    projectId: 'run-balanced-ca5ef',
    storageBucket: 'run-balanced-ca5ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtfsfAya4bNMI9NSjA4pc21C7ZUO2Crk4',
    appId: '1:875660399293:ios:dd2d3ca9d630e2d5105dd4',
    messagingSenderId: '875660399293',
    projectId: 'run-balanced-ca5ef',
    storageBucket: 'run-balanced-ca5ef.firebasestorage.app',
    iosBundleId: 'com.example.runBalanced',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtfsfAya4bNMI9NSjA4pc21C7ZUO2Crk4',
    appId: '1:875660399293:ios:dd2d3ca9d630e2d5105dd4',
    messagingSenderId: '875660399293',
    projectId: 'run-balanced-ca5ef',
    storageBucket: 'run-balanced-ca5ef.firebasestorage.app',
    iosBundleId: 'com.example.runBalanced',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb2qLn0cVAry457HkQOPRmvcuO3SUXP0I',
    appId: '1:875660399293:web:ca79860a7bda63de105dd4',
    messagingSenderId: '875660399293',
    projectId: 'run-balanced-ca5ef',
    authDomain: 'run-balanced-ca5ef.firebaseapp.com',
    storageBucket: 'run-balanced-ca5ef.firebasestorage.app',
    measurementId: 'G-1BS1C3X9GW',
  );
}
